userID_teamID_maps = {
    "omaha/cincinnati": "a_1_0",
    "cincinnati/omaha": "a_1_1",
    "miami/charleston": "a_2_0",
    "charleston/miami": "a_2_1",
    "bozeman/philadelphia": "a_3_0",
    "philadelphia/bozeman": "a_3_1",
    "southbend/stlouis": "a_4_0",
    "stlouis/southbend": "a_4_1",
    "palmsprings/sanfrancisco": "a_5_0",
    "sanfrancisco/palmsprings": "a_5_1",
    "seattle/washington": "a_6_0",
    "washington/seattle": "a_6_1",
    "dallas/yosemite": "a_7_0",
    "yosemite/dallas": "a_7_1",
    "sedona/indianapolis": "b_1_0",
    "indianapolis/sedona": "b_1_1",
    "atlanta/hotsprings": "b_2_0",
    "hotsprings/atlanta": "b_2_1",
    "raleigh/columbus": "b_3_0",
    "columbus/raleigh": "b_3_1",
    "nashville/jackson": "b_4_0",
    "jackson/nashville": "b_4_1",
    "austin/sandiego": "b_5_0",
    "sandiego/austin": "b_5_1",
    "boise/minneapolis": "b_6_0",
    "minneapolis/boise": "b_6_1",
}